import { Task } from '../types';

export interface GoogleCalendarEvent {
  id: string;
  summary: string;
  description?: string;
  start: {
    dateTime?: string;
    date?: string;
  };
  end: {
    dateTime?: string;
    date?: string;
  };
  htmlLink?: string;
}

/**
 * Fetches upcoming events from the user's Google Calendar.
 */
export async function fetchUpcomingEvents(token: string, maxResults = 10): Promise<GoogleCalendarEvent[]> {
  const timeMin = new Date().toISOString();
  const url = `https://www.googleapis.com/calendar/v3/calendars/primary/events?timeMin=${encodeURIComponent(
    timeMin
  )}&maxResults=${maxResults}&singleEvents=true&orderBy=startTime`;

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/json',
    },
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error('Google Calendar List Events Error:', errText);
    throw new Error(`Google Calendar API error: ${response.statusText}`);
  }

  const data = await response.json();
  return (data.items || []) as GoogleCalendarEvent[];
}

/**
 * Creates a Google Calendar Event from a DeadlineAI Task.
 */
export async function createCalendarEvent(token: string, task: Task): Promise<string> {
  const url = 'https://www.googleapis.com/calendar/v3/calendars/primary/events';

  // Set the event start time to 1 hour before the deadline
  const deadlineDate = new Date(task.deadline);
  const startDate = new Date(deadlineDate.getTime() - 60 * 60 * 1000); // 1 hour before

  const body = {
    summary: `⚠️ DeadlineAI: ${task.title}`,
    description: `Task Context: ${task.context}\nComplexity: ${task.complexity.toUpperCase()}\nUrgency Score: ${task.urgencyScore}/10\n\nAI Recommendations:\n${task.aiRecommendation}\n\nGenerated by DeadlineAI.`,
    start: {
      dateTime: startDate.toISOString(),
    },
    end: {
      dateTime: deadlineDate.toISOString(),
    },
    colorId: task.complexity === 'critical' ? '11' : task.complexity === 'high' ? '5' : '9', // Red for critical, Yellow for high, Blue for others
    reminders: {
      useDefault: false,
      overrides: [
        { method: 'popup', minutes: 30 },
        { method: 'email', minutes: 120 },
      ],
    },
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errText = await response.text();
    console.error('Google Calendar Create Event Error:', errText);
    throw new Error(`Google Calendar API error: ${response.statusText}`);
  }

  const data = await response.json();
  return data.id; // Return the created event ID
}

/**
 * Deletes a Google Calendar Event.
 */
export async function deleteCalendarEvent(token: string, eventId: string): Promise<void> {
  const url = `https://www.googleapis.com/calendar/v3/calendars/primary/events/${eventId}`;

  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok && response.status !== 404) {
    const errText = await response.text();
    console.error('Google Calendar Delete Event Error:', errText);
    throw new Error(`Google Calendar API error: ${response.statusText}`);
  }
}
